targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: k_flutter_playground|lib/graphql/pokemon.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: k_flutter_playground|lib/graphql/pokemon.graphql